// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use direct values instead of environment variables for Lovable deployment
const SUPABASE_URL = "https://tjzeskxkqvjbowikzqpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqemVza3hrcXZqYm93aWt6cXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjg0MjcsImV4cCI6MjA2NTkwNDQyN30.T-AV2KidsjI9c1Y7ue4Rk8PxSbG_ZImh7J0uCAz3qGk";

if (!SUPABASE_URL) {
  throw new Error("Missing SUPABASE_URL");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Missing SUPABASE_PUBLISHABLE_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@shared/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Tăng thời gian retry khi có network issues
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      // Giữ session lâu hơn trong localStorage
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      storageKey: 'supabase.auth.token',
    },
    // Retry configuration cho network issues
    global: {
      headers: {
        'x-client-info': 'slide-show-nexus-admin',
      },
    },
  }
);